version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /home/youssef.nouiri/Desktop/Project_Jenkins/jenkins_data:/jenkins_home 
      - /home/youssef.nouiri/Desktop/Project_Jenkins/jenkins:/var/jenkins_config
        
volumes:
  jenkins_data:
    driver: local
  jenkins:
    driver: local